db_file: "bot.db"

bot_url: "https://t.me/Pocketgo_bot"

messages:
  responses:
    start: "Перейди по ссылке: %s"
    already_authorized: "Ты уже авторизирован. Присылай ссылку, а я её сохраню."
    saved_successfully: "Ссылка успешно сохранена"
    unknown_command: "Я не знаю такой команды"
  errors:
    default: "Произошла неизвестная ошибка"
    invalid_url: "Это невалидная ссылка"
    unathorized: "Ты не авторизован, попробуй команду /start"
    unable_to_save: "Увы, не удалось сохранить ссылку, попробуй позже еще раз."